enable-magisk-update = true

[YouTube]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube" 
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
build-mode = "both"
app-name = "YouTube"

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "both"
app-name = "Music"

[Reddit]
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
app-name = "Reddit"

[X]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "Piko"
apkmirror-dpi = "120-640dpi"

[TikTok]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
included-patches = "'SIM spoof'"

[Duolingo]
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
apkmirror-dpi = "120-640dpi"