enable-magisk-update = true
parallel-jobs = 1

[YouTube]
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
included-patches = "'MaterialYou'"
excluded-patches = "'Theme'"
build-mode = "both"
app-name = "YouTube"

[Music]
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "both"
arch = "both"
app-name = "Music"

[Reddit]
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
app-name = "Reddit"

[X]
uptodown-dlurl = "https://twitter.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
patches-source = "crimera/piko"
integrations-source = "crimera/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "Piko"
apkmirror-dpi = "120-640dpi"

[TikTok]
uptodown-dlurl = "https://tiktok.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly"
included-patches = "'SIM spoof'"

[Duolingo]
uptodown-dlurl = "https://duolingo.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/duolingo-duolingo"
apkmirror-dpi = "120-640dpi"

[Soundcloud]
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/soundcloud/soundcloud-soundcloud"